version: "3"
services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run start-dev"
    env_file:
      - .env
    volumes:
    - ./src:/home/node/app/src
    - ./dist:/home/node/app/dist
    ports:
    - "${API_PORT:-3000}:${API_PORT:-3000}"
    - "9229:9229"
    depends_on:
      - mongodb-dev
      - redis-dev
      - build-dev
    networks:
      - worldforge
    links:
      - "mongodb-dev:mongodb"
      - "redis-dev:redis"

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run start"
    env_file:
    - .env
    volumes:
    - ./src:/home/node/app/src
    - ./dist:/home/node/app/dist
    ports:
    - "${API_PORT:-3000}:${API_PORT:-3000}"
    - "9229:9229"
    depends_on:
      - mongodb-prod
      - redis-prod
    links:
      - "mongodb-prod:mongodb"
      - "redis-prod:redis"
    networks:
      - worldforge

  build-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    volumes:
     - ./src:/home/node/app/src
     - ./dist:/home/node/app/dist
    command: "npm run watch"
    networks:
     - worldforge

  build-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
     - ./src:/home/node/app/src
     - ./dist:/home/node/app/dist
    command: "npm run build"
    networks:
     - worldforge

  mongodb-dev:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
    - worldforge

  mongodb-prod:
    image: "mongo:latest"
    ports:
      - "27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - worldforge

  redis-dev:
    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - worldforge

  redis-prod:
    image: "redis:latest"
    ports:
      - "6379"
    volumes:
      - ./data/redis:/data
    networks:
      - worldforge

networks:
  worldforge:
